### PR TITLE
Update README.md file

### PR DESCRIPTION
**Pull request by minhducubc97**
First PR.

### CODE REVIEW

**Comment by TheDash** [comment]
Does the team need access to openrobotics.ca? I still own the website

**Comment by minhducubc97** [comment]
@TheDash Hi! You own the domain openrobotics.ca only I suppose?

**Comment by TheDash** [comment]
Yup! I wish I owned openrobotics.com.. It's worth quite a lot now.

**Comment by minhducubc97** [comment]
@TheDash hey, you mind hang on to that domain for a moment? Our captain is checking if the domain is linked to some of the stuffs we own.

**Comment by minhducubc97** [comment]
@TheDash team captain told me we no longer need access to that domain. You can stop your subscription to it 👌.

**Comment by TheDash** [comment]
No worries. I'll keep it .. if openrobotics.org (OSRF's for-profit business) ever wants it they can buy it from me.

**Pull request merged**
